### ISSUE TITLE
试用报错

### ISSUE THREAD

**Issue by icevivi** [timxx/pywpsrpc#10]
用 deepin V20 装了WPS （通过商店安装）。用 pip3 install pywpsrpc 安装后，试用，报错如下：
icevi@icevi-deepin20:~/downloads/pywpsrpc-master$ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pywpsrpc.rpcwpsapi import (createWpsRpcInstance, wpsapi)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: librpcwpsapi_sysqt5.so: cannot open shared object file: No such file or directory
>>> 

如何安装 librpcwpsapi_sysqt5.so 文件？

**Comment by timxx** [comment]
检查下你安装的WPS路径在哪，是否有librpcwpsapi_sysqt5.so（正常路径应该在/opt/kingsoft/wps-office/office6/librpcwpsapi_sysqt5.so）
PS，最新版本WPS默认带有（仅x64，arm mips之类貌似没有）

**Comment by icevivi** [comment]
文件找到了，上次可能搜索时把文件名搞错了，没搜到
WPS 安装目录是 /opt/apps/cn.wps.wps-office/files/kingsoft/wps-office/office6/
版本是 11.1.0.9505 - Release 正式版
按 readme.md 中的例子导入成功了，但试到
hr, app = rpc.getWpsApplication()
这一句，返回的 app 总是 None

**Comment by timxx** [comment]
没有deepin环境，但是这个路径并非常规的路径，建议先指定
> LD_LIBRARY_PATH=/opt/apps/cn.wps.wps-office/files/kingsoft/wps-office/office6

看看有没有效果
有效果的话可以临时修改一下rpath：
``` sh
patchelf --set-rpath '$ORIGIN:/opt/apps/cn.wps.wps-office/files/kingsoft/wps-office/office6' rpcwpsapi.so
patchelf --set-rpath '$ORIGIN:/opt/apps/cn.wps.wps-office/files/kingsoft/wps-office/office6' rpcwppapi.so
patchelf --set-rpath '$ORIGIN:/opt/apps/cn.wps.wps-office/files/kingsoft/wps-office/office6' rpcetapi.so
patchelf --set-rpath '$ORIGIN:/opt/apps/cn.wps.wps-office/files/kingsoft/wps-office/office6' common.so
```
PS，这几个so为pywpsrpc带的，在python安装目录或者用户目录的site-packages/pywpsrpc目录里（看你安装pywpsrpc到系统还是用户目录）

都不行的话建议先通过官网下载安装试试
PS，需要先确保接受了用户许可协议，且是多组件模式（整合模式有BUG，WPS端的问题）

**Comment by icevivi** [comment]
还是不行。
WPS运行过接受了用户许可协议，但不知道要怎么看是不是多组件模式。

**Comment by timxx** [comment]
通常不同类型的文档可以合在一起（比如WPS跟ET的）就是整合，默认是整合模式吧没记错的话
启动后点那个设置按钮，找到切换窗口管理模式可以切换。。

**Comment by icevivi** [comment]
改成多组件模式也还是不行。
我另找时间从官网下载安装再试试。谢谢~

**Comment by icevivi** [comment]
在官网下了 11.1.0.9615 之后就可以用了，哈哈，谢谢~~

但是有一个问题还想再请教一下，能不能让 hr, app = rpc.getWpsApplication() 执行的时候不显示WPS的启动画面呢？
我试过在这句之后用 app.setVisible(False)，是管用的，但上一句执行的时候WPS的启动画面还是会闪一下。

**Comment by timxx** [comment]
这个目前貌似没办法实现，你可以向WPS官方反馈一下这问题 LoL

**Comment by icevivi** [comment]
好的，谢谢！

**Comment by cent2580** [comment]
> 在官网下了 11.1.0.9615 之后就可以用了，哈哈，谢谢~~
> 
> 但是有一个问题还想再请教一下，能不能让 hr, app = rpc.getWpsApplication() 执行的时候不显示WPS的启动画面呢？
> 我试过在这句之后用 app.setVisible(False)，是管用的，但上一句执行的时候WPS的启动画面还是会闪一下。

老哥，你重装之后就好了吗？我重装之后还是 rpc.getWpsApplication()的app还是返回none，还有是要装qt5吗？

**Comment by icevivi** [comment]
是的，不需要装qt5。你参考说明文档检查一下WPS的模式看是不是没设置好。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "timxx/pywpsrpc"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月3日(星期四) 中午1:35
收件人:&nbsp;"timxx/pywpsrpc"<pywpsrpc@noreply.github.com&gt;;
抄送:&nbsp;"按钮工厂"<icevi.icevi@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [timxx/pywpsrpc] 试用报错 (#10)





  
在官网下了 11.1.0.9615 之后就可以用了，哈哈，谢谢~~
 
但是有一个问题还想再请教一下，能不能让 hr, app = rpc.getWpsApplication() 执行的时候不显示WPS的启动画面呢？
 我试过在这句之后用 app.setVisible(False)，是管用的，但上一句执行的时候WPS的启动画面还是会闪一下。
  
老哥，你重装之后就好了吗？我重装之后还是 rpc.getWpsApplication()的app还是返回none，还有是要装qt5吗？

**Comment by fahaihappy** [comment]
这个无界面运行的画怎么设置WPS的模式呢？

**Comment by zhoulei135770** [comment]
我想增加一个docm格式的转换

**Comment by zhoulei135770** [comment]
如果能把这个闪过的画面去掉，就完美了

**Comment by zcgg2zhmm** [comment]
> 通常不同类型的文档可以合在一起（比如WPS跟ET的）就是整合，默认是整合模式吧没记错的话
> 启动后点那个设置按钮，找到切换窗口管理模式可以切换。。

那如果是没有界面的Linux呢？

**Comment by zcgg2zhmm** [comment]
> 这个无界面运行的话怎么设置WPS的模式呢？

同问！请问这个问题您解决了吗？

**Comment by icevivi** [comment]
WPS的模式还是按上面的设置，好象还做不到完全无界面运行，会有个启动界面闪一下，但闪过之后其实是看不到WPS的界面的。


不知道现在WPS有没有提供新接口可以做到不显示那个启动界面。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "timxx/pywpsrpc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月25日(星期天) 中午12:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [timxx/pywpsrpc] 试用报错 (#10)





  
这个无界面运行的话怎么设置WPS的模式呢？
  
同问！请问这个问题您解决了吗？

**Comment by zcgg2zhmm** [comment]
> WPS的模式还是按上面的设置，好象还做不到完全无界面运行，会有个启动界面闪一下，但闪过之后其实是看不到WPS的界面的。 不知道现在WPS有没有提供新接口可以做到不显示那个启动界面。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "timxx/pywpsrpc" ***@***.***&gt;; 发送时间:&nbsp;2021年4月25日(星期天) 中午12:39 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [timxx/pywpsrpc] 试用报错 (#10) 这个无界面运行的话怎么设置WPS的模式呢？ 同问！请问这个问题您解决了吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

因为我的服务器是无ui的linux，不知道怎么设置成那个 多组件模式

**Comment by cent2580** [comment]
你好，我想问下如何通过命令或者改wps配置文件切换多组件模式

**Comment by landv** [comment]
> 没有deepin环境，但是这个路径并非常规的路径，建议先指定
> 
> > LD_LIBRARY_PATH=/opt/apps/cn.wps.wps-office/files/kingsoft/wps-office/office6
> 
> 看看有没有效果 有效果的话可以临时修改一下rpath：
> 
> ```shell
> patchelf --set-rpath '$ORIGIN:/opt/apps/cn.wps.wps-office/files/kingsoft/wps-office/office6' rpcwpsapi.so
> patchelf --set-rpath '$ORIGIN:/opt/apps/cn.wps.wps-office/files/kingsoft/wps-office/office6' rpcwppapi.so
> patchelf --set-rpath '$ORIGIN:/opt/apps/cn.wps.wps-office/files/kingsoft/wps-office/office6' rpcetapi.so
> patchelf --set-rpath '$ORIGIN:/opt/apps/cn.wps.wps-office/files/kingsoft/wps-office/office6' common.so
> ```
> 
> PS，这几个so为pywpsrpc带的，在python安装目录或者用户目录的site-packages/pywpsrpc目录里（看你安装pywpsrpc到系统还是用户目录）
> 
> 都不行的话建议先通过官网下载安装试试 PS，需要先确保接受了用户许可协议，且是多组件模式（整合模式有BUG，WPS端的问题）


```shell
cd /opt/apps/cn.wps.wps-office/files/kingsoft/wps-office/office6
sudo patchelf --set-rpath '$ORIGIN:/opt/apps/cn.wps.wps-office/files/kingsoft/wps-office/office6' librpcwpsapi.so
sudo patchelf --set-rpath '$ORIGIN:/opt/apps/cn.wps.wps-office/files/kingsoft/wps-office/office6' librpcwppapi.so
sudo patchelf --set-rpath '$ORIGIN:/opt/apps/cn.wps.wps-office/files/kingsoft/wps-office/office6' librpcetapi.so
```

**Comment by fahaihappy** [comment]
您好  您的邮件我已收到   谢谢！！！

**Comment by fahaihappy** [comment]
您好  您的邮件我已收到   谢谢！！！
