### ISSUE TITLE
怎样无界面运行？

### ISSUE THREAD

**Issue by youkie** [timxx/pywpsrpc#11]
ssh登录到linux服务器上面，只有开启x11-forward，wps界面能弹出来的情况下才能运行成功。怎么样才能不弹出wps的窗口，完全在命令行下面运行呢？

**Comment by timxx** [comment]
请自行搜索安装个假的x11（xf86-video-dummy）

**Comment by tyjuncai** [comment]
您能不能具体说明下如果解决? 我这边想通过docker镜像运行，也是完全命令行下运行，如果解决这个问题？谢谢了

**Comment by tyjuncai** [comment]
> 请自行搜索安装个假的x11（xf86-video-dummy）

您能不能具体说明下如果解决? 我这边想通过docker镜像运行，也是完全命令行下运行，如果解决这个问题？谢谢了

**Comment by timxx** [comment]
https://github.com/timxx/pywpsrpc/wiki/Run-on-Server
