### ISSUE TITLE
遇到一个错误ImportError: libQt5Xml.so.5

### ISSUE THREAD

**Issue by cent2580** [timxx/pywpsrpc#12]
[**Describe](url) the bug**
File “convertto.py” ,line 19, in<module>
    from pywpsrpc.rpcwpsapi import (createWpsRpcInstance,wpsapi)
ImportError: libQt5Xml.so.5: cannot open shared object file: No such file or [directory]

**Environment**
 - Distribution: [ Ubuntu 20.04.1]
 - Versions: [ pywpsrpc 1.0.2, WPS Office 11.1.0.9615]
 - Installed from pip: [yes]

**Comment by timxx** [comment]
Qt5安装没有？SDK本身依赖Qt5的

**Comment by timxx** [comment]
信息不足
