### ISSUE TITLE
看了一下，没有可以编辑excel和powerpoint的api，而且编辑word的api和例程感觉好简单啊！

### ISSUE THREAD

**Issue by 123dbl** [timxx/pywpsrpc#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by timxx** [comment]
都有的，只不过没写例子（tests里有一些），
详细API文档参考官方文档，readme有写，
您也可以帮忙添加一些demo
