### ISSUE TITLE
运行示例py报错NoneType' object has no attribute 'Documents'

### ISSUE THREAD

**Issue by xiaobing395845388** [timxx/pywpsrpc#15]
x86 centos7下执行示例py新建docx文件报错，弹出的wpsUI有wps和新建两个页签，wps页签下空白页，手动再点击下wps正常
手动运行wps正常

**Comment by ColonelDarcy2018** [comment]
> x86 centos7下执行示例py新建docx文件报错，弹出的wpsUI有wps和新建两个页签，wps页签下空白页，手动再点击下wps正常
> 手动运行wps正常

怎么解决的，我在deepin 也遇到了同样的问题
