### ISSUE TITLE
docker container 提示 wps: cannot connect to X server

### ISSUE THREAD

**Issue by woshishipeiyu** [timxx/pywpsrpc#16]
非常感谢您对上一个issue的回答，这几天又开始使用wps4linux， 我参考了https://code.aliyun.com/zouyingfeng/wps/tree/master/cpp 上的demo，写了一个小的可执行程序并且准备用带桌面的ubuntu docker image来安装wps， 按照dockerfile的过程结束后，我进入container并且执行我写的小工具，结果提示无法连接xserver，但是当我进入container的vnc桌面，在桌面里的命令行执行时，小工具正常运行，请问有什么解决办法吗
我注意到demo里BSTR StrWpsAddress = SysAllocString(__X("/opt/kingsoft/wps-office/office6/wps"));这句话，这个应用是否是必须要在桌面被显示出来才能够被调用，可以换成其他.a 或者.o吗
ps 我得程序就是简单把一个.wps另存成.docx pdf等格式

**Comment by timxx** [comment]
WPS本身依赖桌面环境的，没有安装是跑不起来的~当然你可以尝试其它方案（如：dummy video driver）

**Comment by python-yang** [comment]
> WPS本身依赖桌面环境的，没有安装是跑不起来的〜当然你可以尝试其他方案（如：dummy video driver）

关于 dummy video driver 或虚拟显示可以多点提示吗，打包成docker 命令行无法运行，桌面可以运行，难受了一天了……

**Comment by timxx** [comment]
https://github.com/timxx/pywpsrpc/wiki/Run-on-Server

**Comment by ykfs** [comment]
在linux无图形界面程序下安装了dummy video driver，运行X时，有报错，有遇到过吗，可以用虚拟机centos7尝试
![image](https://user-images.githubusercontent.com/5036047/106106448-80d3bb80-6180-11eb-8ac4-2239c0cdca7c.png)
