### ISSUE TITLE
getWppApplication 使用 app.Visible = False 报错

### ISSUE THREAD

**Issue by python-yang** [timxx/pywpsrpc#17]
hr, rpc = createWppRpcInstance()
    if hr != S_OK:
        raise ConvertException("Can't create the rpc instance", hr)

    hr, app = rpc.getWppApplication()
    if hr != S_OK:
        raise ConvertException("Can't get the application", hr)
    # we don't need the gui
    app.Visible = False
根据word 转pdf的项目修改为 ppt转pdf 目前已经完成了转化的demo不过在打来wps 后使用Visible 参数设置时出现错误。内容如下：
AttributeError: Call 'put_Visible()' failed with 0x80010105
使用app.setVisible(False) 也会抛出同样的错误

**Comment by timxx** [comment]
这应该不是问题的，WPP本身不允许通过API隐藏窗口（包含MS Powerpoint），至少裸调C++ API也是失败的
不过WPP可以通过app.Presentations.Open指定WithWindow=False不显示文档窗口（但不是程序的）
 PS，Windows下默认启动是隐藏状态，这一点你可以给WPS官方反馈 :)
