### ISSUE TITLE
并发执行文件转换的程序获取不到application

### ISSUE THREAD

**Issue by xiaobing395845388** [timxx/pywpsrpc#18]
单个线程文件转换没有问题，并发执行的时候会报错获取不到application，请问能是什么原因

**Comment by timxx** [comment]
还没时间看，可能是SDK本身不支持多线程，你可以换成multiprocessing看看

**Comment by xiaobing395845388** [comment]
multiprocessing在哪里设置  wps软件中吗 还是程序里呀？

**Comment by timxx** [comment]
我意思是python由多线程换多进程（可以搜索一下）

**Comment by xiaobing395845388** [comment]
明白了，咱们提供的示例里能丰富下这块不

**Comment by xiaobing395845388** [comment]
目前使用的是uvicorn  配合的多个worker 是多进程的，出现的这个问题，改成单worker没问题的

**Comment by timxx** [comment]
提供下demo?

**Comment by xiaobing395845388** [comment]
> 提供下demo?

https://github.com/xiaobing395845388/convert-wps  这是个demo程序

**Comment by xiaobing395845388** [comment]
> 提供下demo?

有啥进展不@_@

**Comment by timxx** [comment]
你给的demo跑不起来

**Comment by timxx** [comment]
修改跑起来后没发现什么问题，网页上选多个文件代码貌似只处理了一个，多次打开都能正常转换
ArchLinux

**Comment by xiaobing395845388** [comment]
恩  网页上那个是测试单文件的    实际是在jemeter或者代码中并发调用demo中的接口

**Comment by xiaobing395845388** [comment]
或者手动打开多个页面   用大一点的文档转换复现

**Comment by xiaobing395845388** [comment]
或者这样运行example下的convertto.py，也会报错
```
#!/bin/bash

for ((i=0;i<5;i++));do

{
python3 convertto.py --format "pdf" README.md && echo ”done!”

} &

done

wait
```

**Comment by xiaobing395845388** [comment]
@timxx  你好  上面的脚本试了没  是wps sdk本身就不支持多开并发操作吗？

**Comment by timxx** [comment]
看了下应该是WPS本身的BUG（或者SDK），你可以查看一下启动的进程-rpcserverport参数都一样，应该是冲突了导致其它进程取不到application（这个应该是每次起来不一样）

**Comment by xiaobing395845388** [comment]
> 看了下应该是WPS本身的BUG（或者SDK），你可以查看一下启动的进程-rpcserverport参数都一样，应该是冲突了导致其它进程取不到application（这个应该是每次起来不一样）

有啥办法解决吗

**Comment by timxx** [comment]
你可以先给WPS官方反馈一下吧。
另外可以考虑下换种方案，不要同时启动多个进程，比如单个进程重复利用之类的

**Comment by xiaobing395845388** [comment]
> 看了下应该是WPS本身的BUG（或者SDK），你可以查看一下启动的进程-rpcserverport参数都一样，应该是冲突了导致其它进程取不到application（这个应该是每次起来不一样）

请问-rpcserverport参数一样 是怎么看出来的？

**Comment by YihengLiu1996** [comment]
> @timxx 你好 上面的脚本试了没 是wps sdk本身就不支持多开并发操作吗？

兄弟，我也遇到了并发运行的问题，想请教一下，后来你解决了吗？
