### ISSUE TITLE
How to run on server

### ISSUE THREAD

**Issue by 2ndpic** [timxx/pywpsrpc#19]
> Please note that you have to accept the EULA display by WPS Office, otherwise you may failed to run pywpsrpc. You can find how to accept it without showing the WPS Office interface.

请问在没有界面的Ubantu上面如何接受EULA，我没有找到解决方法，此前我已经执行了

1. apt install xserver-xorg-video-dummy

2.create a configuration file

3.start the Xorg (with root):

执行`convertto.py README.md -f pdf`的时候报错了

`
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    hr, doc = app.Documents.Add()
AttributeError: 'NoneType' object has no attribute 'Documents'
`

我认为这是我没有接受EULA导致的

**Comment by timxx** [comment]
你手工对比下wps接受前后配置文件，也许是写在那了

**Comment by zcgg2zhmm** [comment]
同问啊！！解决不了诶

**Comment by tyjuncai** [comment]
+1

**Comment by tyjuncai** [comment]
> 你手工对比下wps接受前后配置文件，也许是写在那了

找到了，多谢

**Comment by Zhangts98** [comment]
> > 你手工对比下wps接受前后配置文件，也许是写在那了
> 
> 找到了，但是遇到新问题，使用非root用户运行貌似不行。

请问是如何修改的，才能让docker 接受EULA

**Comment by mjTree** [comment]
> > > 你手工对比下wps接受前后配置文件，也许是写在那了
> > 
> > 
> > 找到了，但是遇到新问题，使用非root用户运行貌似不行。
> 
> 请问是如何修改的，才能让docker 接受EULA



> > 你手工对比下wps接受前后配置文件，也许是写在那了
> 
> 找到了，但是遇到新问题，使用非root用户运行貌似不行。

在哪里呀，能告知一下不？

**Comment by mjTree** [comment]
> > 你手工对比下wps接受前后配置文件，也许是写在那了
> 
> 找到了，但是遇到新问题，使用非root用户运行貌似不行。

文件是什么呀，能否告知一下，谢谢

**Comment by zcgg2zhmm** [comment]
> > 你手工对比下wps接受前后配置文件，也许是写在那了
> 
> 找到了，但是遇到新问题，使用非root用户运行貌似不行。

@tyjuncai 请问你是在哪里找到的？

**Comment by Scott-zhangjs** [comment]
> > > 你手工对比下wps接受前后配置文件，也许是写在那了
> > 
> > 
> > 找到了，但是遇到新问题，使用非root用户运行貌似不行。
> 
> @tyjuncai 请问你是在哪里找到的？
配置文件位置 /root/.config/Kingsoft/Office.conf
添加下面的接受协议 ，亲测可以跳过，也可以把自己能用的替换掉Office.conf
common\AcceptedEULA=true

**Comment by zcgg2zhmm** [comment]
> 



> > > > 你手工对比下wps接受前后配置文件，也许是写在那了
> > > 
> > > 
> > > 找到了，但是遇到新问题，使用非root用户运行貌似不行。
> > 
> > 
> > @tyjuncai 请问你是在哪里找到的？
> 
> 配置文件位置 /root/.config/Kingsoft/Office.conf 添加下面的接受协议 ，亲测可以跳过，也可以把自己能用的替换掉Office.conf common\AcceptedEULA=true

非常感谢

**Comment by verydemo** [comment]
> 你手工对比下wps接受前后配置文件，也许是写在那了

我没有找到配置文件 /root/.config/Kingsoft/Office.conf
