### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'put_Visible'

### ISSUE THREAD

**Issue by l1shen** [timxx/pywpsrpc#2]
使用例子 convertto 报错
```
root@a3e30ee72ca8:/home/root# python3 conv.py --format "pdf" test.md
Traceback (most recent call last):
  File "conv.py", line 104, in <module>
    main()
  File "conv.py", line 94, in main
    convert_to(args.path, args.format, args.abort)
  File "conv.py", line 41, in convert_to
    app.Visible = False
  File "/usr/local/lib/python3.6/dist-packages/pywpsrpc/utils.py", line 120, in __setattr__
    hr = getattr(self._object, "put_" + name)(value)
AttributeError: 'NoneType' object has no attribute 'put_Visible'
```

**Comment by timxx** [comment]
看日志，这不是直接跑的原demo吧？
1、请确认原demo是否有问题
2、确认直接运行WPS是否正常
3、打印下rpc.getWpsApplication()返回值
4、在非root帐号运行是否有问题

**Comment by l1shen** [comment]
我复制了原 demo 的代码再试了一次
打印了 rpc.getWpsApplication() 的返回值
![image](https://user-images.githubusercontent.com/8299540/76676552-b1aa1100-65ff-11ea-80e7-5ee81f57b881.png)

**Comment by timxx** [comment]
额。。打印时不要加RpcProxy，这样看不到原始返回值

**Comment by l1shen** [comment]
> 额。。打印时不要加RpcProxy，这样看不到原始返回值

![image](https://user-images.githubusercontent.com/8299540/76678445-0440f880-6613-11ea-897c-18b5668b4ca5.png)

**Comment by timxx** [comment]
建议安装下pyside2，如果你用的发行版没有，可以安装pyqt5，然后`from PySide2.QtCore import QCoreApplication`改成`from PyQt5.QtCore import QCoreApplication`看看
如果问题解决的话，那你就需要安装这其中一个依赖。。这是wps的SDK实现依赖，pywpsrpc这边无法去除，ps，我这边的ArchLinux机器是不需要的。。

**Comment by l1shen** [comment]
> 建议安装下pyside2，如果你用的发行版没有，可以安装pyqt5，然后`from PySide2.QtCore import QCoreApplication`改成`from PyQt5.QtCore import QCoreApplication`看看
> 如果问题解决的话，那你就需要安装这其中一个依赖。。这是wps的SDK实现依赖，pywpsrpc这边无法去除，ps，我这边的ArchLinux机器是不需要的。。

之前是一直安装了 pyside2 的，然后我刚刚换了 pyqt5 也没有解决问题报错也几乎相同
![image](https://user-images.githubusercontent.com/8299540/76678927-0442f780-6617-11ea-8830-ec9c1e3d3cca.png)

不过不知道有没有跟安装完 pyside2 或者 pyqt5 的一个报错有关，它们都会报一个找不到 `Qt_5.14` 的错误
![image](https://user-images.githubusercontent.com/8299540/76678952-3a807700-6617-11ea-9c38-b3543bc0b909.png)
需要我去设置一下 `LD_LIBRARY_PATH` 为 `pyside2` 或者 `pyqt5` 的 `Qt/lib` 目录才不报错

**Comment by timxx** [comment]
你报的这个错误应该是你安装的pyside2/pyqt5依赖的qt5版本过高导致的（就是你系统安装的Qt5版本低）。。建议通过系统包管理安装pyside2或者pyqt5

现在原因是getWpsApplication失败了（调用的WPS SDK），看起来是因为没有QApplication导致没有等待wps进程起来就返回了
你可以先试一下另一个demo是不是能够正常起来界面

**Comment by l1shen** [comment]
另外一个 demo 是可以正常运行的

**Comment by timxx** [comment]
能把wps窗口嵌入过来？
另外提供一下你系统环境，是自己编译pywpsrpc还是通过pip安装

**Comment by l1shen** [comment]
系统是 `Ubuntu 18.04.1`
`pywpsrpc` 是通过 `pip` 安装

**Comment by timxx** [comment]
我在虚拟机安装了个Ubuntu 18.04跑是正常的，但是没有安装pyside2或者pyqt5，你可以注掉PySide2相关import及使用代码看看

**Comment by l1shen** [comment]
我也重新安装了一个 ubuntu 18.04 虚拟机，然后只安装了 pywpsrpc 
接下来调用 demo 代码报
![image](https://user-images.githubusercontent.com/8299540/76737545-eeaf0880-67a3-11ea-8563-6bd1d67ee55a.png)
然后我安装了 libqt5gui5 和 libqt5xml5 再去调用代码就会报和之前一样的错误
![image](https://user-images.githubusercontent.com/8299540/76737651-228a2e00-67a4-11ea-8a95-58859059001e.png)

**Comment by timxx** [comment]
或者你共享一下你的虚拟机？

**Comment by timxx** [comment]
wps的bug，需要切换到多组件模式
