### ISSUE TITLE
使用api  doc.open(path,readonly=false)的时候打开office2003的doc文件报错，用wps界面能打开

### ISSUE THREAD

**Issue by xiaobing395845388** [timxx/pywpsrpc#20]
用wps界面打开应该是启用了兼容模式，api里能处理吗

**Comment by timxx** [comment]
提供下样张？

**Comment by xiaobing395845388** [comment]
https://pan.baidu.com/s/1gcLpeioizWyPnAITDzq3XA   提取码y5hn

**Comment by timxx** [comment]
我这边试了下是直接能打开的 :)

**Comment by xiaobing395845388** [comment]
> 我这边试了下是直接能打开的 :)

wps界面是直接能打开，程序里open的时候报错 打不开

**Comment by timxx** [comment]
是不是你调用的API写错了？至少你标题的看起来是不对的，大小写之类的
Documents.Open打开没报错

**Comment by xiaobing395845388** [comment]
> 是不是你调用的API写错了？至少你标题的看起来是不对的，大小写之类的
> Documents.Open打开没报错

hr, doc = docs.Open(path, ReadOnly=True) ,标题我手写的  大小写没注意，程序里这样，其他的docx文件打开正常，就doc格式的文件报错

**Comment by xiaobing395845388** [comment]
错误代码是  0x80000008

**Comment by timxx** [comment]
我这边没有报错 LoL

**Comment by xiaobing395845388** [comment]
解决了，真是见鬼了，doc文件相对路径就不行绝对路径就可以，docx文件绝对路径和相对路径都可以

**Comment by zcgg2zhmm** [comment]
没有ui的ubuntu能用吗？
