### ISSUE TITLE
不能获取app

### ISSUE THREAD

**Issue by aixuedegege** [timxx/pywpsrpc#21]
您好，请问我
```python
hr, rpc = createWpsRpcInstance()
rpc.getWpsApplication()```

返回一个负数和None，请问是为什么？应该如何解决

**Comment by timxx** [comment]
什么环境？安装WPS的WPS能否正常起来

**Comment by aixuedegege** [comment]
centos7 服务器上安装的”wps-office-11.1.0.9719-1.x86_64.rpm“这个。没有gui界面，纯command的。

**Comment by timxx** [comment]
pywpsrpc依赖WPS，而WPS依赖GUI，在服务器是不能跑的
如果你想折腾可以参考README [在服务器上运行](https://github.com/timxx/pywpsrpc/wiki/Run-on-Server)

**Comment by aixuedegege** [comment]
好的 多谢

**Comment by suqi95716aa** [comment]
> 你好，我遇到了同样的问题，下面是我的环境：

**Comment by suqi95716aa** [comment]
> 

切换到多组件模式已解决，设置多组件模式流程：打开wps → 右上角设置按钮 → Settings → Others → Change window manage mode… → 选择【Multi-Module Mode】

**Comment by Una-zh** [comment]
> 您好，请问我
> 
> ```python
> hr, rpc = createWpsRpcInstance()
> rpc.getWpsApplication()```
> 
> 返回一个负数和None，请问是为什么？应该如何解决
> ```

请问您解决了吗？我现在也遇到相同的问题，centos7

**Comment by aixuedegege** [comment]
> > 您好，请问我
> > ```python
> > hr, rpc = createWpsRpcInstance()
> > rpc.getWpsApplication()```
> > 
> > 返回一个负数和None，请问是为什么？应该如何解决
> > ```
> 
> 请问您解决了吗？我现在也遇到相同的问题，centos7

楼上说了服务器跑不起来 就没折腾啦

**Comment by Una-zh** [comment]
> > > 您好，请问我
> > > ```python
> > > hr, rpc = createWpsRpcInstance()
> > > rpc.getWpsApplication()```
> > > 
> > > 返回一个负数和None，请问是为什么？应该如何解决
> > > ```
> > 
> > 
> > 请问您解决了吗？我现在也遇到相同的问题，centos7
> 
> 楼上说了服务器跑不起来 就没折腾啦

我今天下午给折腾出来了😂

**Comment by SilentMoebuta** [comment]
> > > > 您好，请问我
> > > > ```python
> > > > hr, rpc = createWpsRpcInstance()
> > > > rpc.getWpsApplication()```
> > > > 
> > > > 返回一个负数和None，请问是为什么？应该如何解决
> > > > ```
> > > 
> > > 
> > > 请问您解决了吗？我现在也遇到相同的问题，centos7
> > 
> > 
> > 楼上说了服务器跑不起来 就没折腾啦
> 
> 我今天下午给折腾出来了😂

怎么搞的  求教一下
