### ISSUE TITLE
有保护密码的文档，调用open的API会一直卡主

### ISSUE THREAD

**Issue by xiaobing395845388** [timxx/pywpsrpc#23]
open函数支持打开文件输入保护密码的操作吗  或者有返回值不可以告知程序处于输入保护密码状态

**Comment by timxx** [comment]
似乎没有这么一个API，但是你可以通过输入一个错误的密码饶过，比如
`hr, doc = app.Documents.Open(theDocPath, PasswordDocument="xxx", ReadOnly=True)`
如果文档没有密码，是可以直接打开，如果有密码但是不对就会返回失败，ReadOnly=True这个只是确保万一密码对了还有一层写密码时可以只读打开，你要写的话就可能做不了了

**Comment by timxx** [comment]
如果是明确知道密码，直接用前面说的PasswordDocument参数就好了

**Comment by xiaobing395845388** [comment]
好像不行啊，```hr, doc = docs.Open(path, PasswordDocument="XXXX", ReadOnly=True)```，密码错误的时候不会返回失败，程序还是一直阻塞状态，UI上输入密码弹出框一直显示

**Comment by timxx** [comment]
我这里用的版本是没有问题的，如果跟文档有关的话，你自己制作个加密的文档试试？
