### ISSUE TITLE
读取wps内容

### ISSUE THREAD

**Issue by BorisGao96** [timxx/pywpsrpc#25]
问一下 是否存在读取 .wps .et 等wps特定格式的文件方法，相关文档太少，找不到。

**Comment by gaoqifa1996** [comment]
tests 目录下的测试方法里 也只有创建的相关类方法 大佬能解答一下吗

**Comment by timxx** [comment]
api打开文档是不区分格式的，只区分项目。

文档ReadMe有写，可以去https://open.wps.cn/docs/office 或者 https://docs.microsoft.com/en-us/office/vba/api/overview/ 这里看，
也可以用help对某个类查看
