### ISSUE TITLE
are there pywpsrpc wheel files based on python35 and architecture like aarch64 or mips64

### ISSUE THREAD

**Issue by hellobw2000** [timxx/pywpsrpc#26]
I need pywpsrpc aarch64 wheels and mips64el wheels based on python35, but I have no enviroment to build them from source code, Is there anyone has built the wheel? please share me. thank you!

**Comment by timxx** [comment]
If you have arch64/mips64el machine, and the correspond WPS version, you can build yourself. LoL
For python 3.5, you should use py35 branch
