### ISSUE TITLE
Failed to build and prompting " cannot find -lrpcwpsapi_sysqt5“

### ISSUE THREAD

**Issue by will6686** [timxx/pywpsrpc#27]
**Describe the bug**

**To Reproduce**
sip-build

**Expected behavior**

**Screenshots**
![Uploading image.png…](build error message)

**Environment**
 - Distribution: [e.g. Ubuntu 18.04]
 - Versions: [e.g. pywpsrpc 1.0.2, WPS Office 11.1.0.9126]
 - Installed from pip: [yes/build from source]

**Comment by will6686** [comment]
* Qt version:
``` 
$ qmake -v
QMake version 3.1
Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu
```

**Comment by will6686** [comment]
Failed to install wps

**Comment by hellobw2000** [comment]
I have the same issue about building source code, cannot find -lrpcwpsapi_sysqt5
how did you fix it ?
