### ISSUE TITLE
Failed to build and prompting " cannot find -lrpcwpsapi_sysqt5“

### ISSUE THREAD

**Issue by hellobw2000** [timxx/pywpsrpc#28]
**Describe the bug**

**To Reproduce**
sip-build

**Expected behavior**

**Screenshots**

**Environment**
 - Distribution: [e.g. os:Kylin V10, arch:mips64 kernel:Linux 4.4.131-20200429.kylin.desktop-generic]
 - Versions: [e.g. pywpsrpc 2.2.0, WPS Office 11.1.0.10161_mips64el]
 - Installed from pip: [no/build from source]
qmake -v
qmake version 2.01a
using qt version 4.8.7 in /usr/lib/mips64el-linux-gnu

**Comment by timxx** [comment]
Please confirm whether your WPS version have the sdk or not:

- librpcetapi_sysqt5.so
- librpcwppapi_sysqt5.so
- librpcwpsapi_sysqt5.so

They placed inside office6 folder normally. As I known the WPS community version for arm/mips doesn't include the sdk.

**Comment by hellobw2000** [comment]
> Please confirm whether your WPS version have the sdk or not:
> 
> * librpcetapi_sysqt5.so
> * librpcwppapi_sysqt5.so
> * librpcwpsapi_sysqt5.so
> 
> They placed inside office6 folder normally. As I known the WPS community version for arm/mips doesn't include the sdk.


there is no such so file under path /opt/kingsoft/wps-office/office6
so WPS cann't not support sdk for arm/mips, and pywpsrpc can't work for arm/mips ?

**Comment by hellobw2000** [comment]
> Please confirm whether your WPS version have the sdk or not:
> 
> * librpcetapi_sysqt5.so
> * librpcwppapi_sysqt5.so
> * librpcwpsapi_sysqt5.so
> 
> They placed inside office6 folder normally. As I known the WPS community version for arm/mips doesn't include the sdk.

我在mips安装了专业版的wps wps-office_11.8.2.9479.professional.preload.num.ndm.all.withsn_mips64el.deb,  /opt/kingsoft/wps-office/office6 路径下有三个so文件。我用sip-wheel打包了pywpsrpc,没有报错，用pip install [安装的时候报错，说当前平台不支持这个包，详情见附件，我在另一个国产机mips上直接解压之后打成deb包强制安装，运行python脚本的时候报错，找不到wpsapp，和问题29一样的错，帮忙分析下是什么原因呢

![pip install err](https://user-images.githubusercontent.com/82930822/116054587-64c3b580-a6ae-11eb-9b9f-52c467ea26c6.jpg)

**Comment by timxx** [comment]
最新代码已对这个库链接做了调整，目前官方未提供x64外的SDK库，所以这里也不会支持。。
