### ISSUE TITLE
我想用这个来在linux上操作excel

### ISSUE THREAD

**Issue by lizhi2013** [timxx/pywpsrpc#3]
所以想知道是否能够 比如打开一个excel，复制到另外一个excel，然后公式不丢

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lizhi2013** [comment]
另外能不能支持python 2.7版本啊

**Comment by timxx** [comment]
目前没有计划也没有时间去支持2.x系列的python哈，毕竟都不更新了吧
至于操作问题，可以搜索一下excel的vba文档，稍微改一下就可以在pyrhon下用了
PS，我对excel的api不熟悉
