### ISSUE TITLE
您好！请问有没有接口文档什么的提供一下？不然不知道代码怎么写～

### ISSUE THREAD

**Issue by zcgg2zhmm** [timxx/pywpsrpc#30]
比如说，我想在新的tab里面打开另外一个word文件，这个改代码该怎么写？
比如说，关闭一个标签代码怎么写？

**Comment by timxx** [comment]
README有写，因为是封装C++的接口，使用方法跟C++几乎是一致的（除了一些属性之类的方法可以直接当属性使用）
参见[WPS 基础接口](https://open.wps.cn/docs/office)

**Comment by zcgg2zhmm** [comment]
> README有写，因为是封装C++的接口，使用方法跟C++几乎是一致的（除了一些属性之类的方法可以直接当属性使用）
> 参见[WPS 基础接口](https://open.wps.cn/docs/office)

好的！谢谢！！

**Comment by zcgg2zhmm** [comment]
忘记关闭了，谢谢！！
