### ISSUE TITLE
资源没有释放

### ISSUE THREAD

**Issue by cole-dda** [timxx/pywpsrpc#33]
当调用：hr, app = rpc.getWpsApplication()
失败的时候，wps进程不会被自动杀死。

所以，如果因为某些原因无法成功执行上面的操作，系统就会存在越来越多的wps进程，但是因为app==None，所以
调用者无法释放。

**Comment by timxx** [comment]
裸调c++ sdk是不是也有一样的问题呢？目前官方sdk没看到相关接口，可能需要杀进程:(

**Comment by cole-dda** [comment]
不会c++，老板可以帮忙完善一下？

**Comment by timxx** [comment]
可以参考[这里](https://github.com/timxx/pywpsrpc/blob/master/examples/rpcetapi/et_convert.py#L52)的方法获取进程id，然后杀掉
