### ISSUE TITLE
执行convertto.py 会跳出wps进程

### ISSUE THREAD

**Issue by czxichen** [timxx/pywpsrpc#35]
执行时会弹出wps ui然后手动关闭的话就会返回  can't get the application 错误。

**Comment by timxx** [comment]
这个是wps的行为，目前linux版本不能默认隐藏窗口，如果你知道怎么实现，欢迎PR

**Comment by czxichen** [comment]
启动的时候命令参数可以指定隐藏ui, sip 语法看不懂所以提不了PR

**Comment by Naslang** [comment]
@czxichen 请问参数是怎么传的？我也遇到了同样的问题，会闪wps的启动界面

**Comment by czxichen** [comment]
> 

忘记了，当时就随便玩玩没放心上搞，好像是直接调用动态库方法里面传的参数

**Comment by seiuneko** [comment]
@czxichen 请问当初传的命令行参数是什么，或者给个搜索关键词也可以。感谢回答。
