### ISSUE TITLE
excel文件转换pdf文件存在问题

### ISSUE THREAD

**Issue by mjTree** [timxx/pywpsrpc#38]
**Describe the bug**
excel文件转换pdf文件时，代码执行完毕后pdf文件并没有生成.

**To Reproduce**
result, excel_rpc = createEtRpcInstance()
result, excel_app = excel_rpc.getEtApplication()
workbooks = app_excel.Workbooks
result, workbook = workbooks.Open('1.xls')
workbook.SaveAs(Filename='1.pdf, FileFormat=etapi.xlTypePDF)

**Expected behavior**
我使用workbook的SaveAs实现了xls xlsx csv等文件格式转换，但是pdf文件却无法生成。

**Screenshots**

**Environment**
 - Distribution: [docker Ubuntu 20]
 - Versions: [e.g. pywpsrpc 2.3.1, WPS Office 11.1.0.9126]
 - Installed from pip: [yes]

**Comment by qbmzc** [comment]
ret = doc.ExportAsFixedFormat(etapi.XlFixedFormatType.xlTypePDF, new_file)
excel保存为pdf是这个方法
