### ISSUE TITLE
libQt5Core.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by NanZhang1991** [timxx/pywpsrpc#39]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Environment**
 - Distribution: [e.g. Ubuntu 18.04]
 - Versions: [e.g. pywpsrpc 1.0.2, WPS Office 11.1.0.9126]
 - Installed from pip: [yes/build from source]

**Comment by timxx** [comment]
你得自己安装qt5

**Comment by NanZhang1991** [comment]
谢谢，我已经解决

Weitian Leung ***@***.***> 于2021年11月5日周五 下午9:32写道：

**Comment by kerneltravel** [comment]
according to [this page](https://qbmzc.github.io/2022/05/06/2022/05/061908/)
```
apt-get install libqt5core5a
strip --remove-section=.note.ABI-tag /lib/x86_64-linux-gnu/libQt5Core.so.5
```
