### ISSUE TITLE
关于pywpsrpc是必须依赖qt5吗，可以qt4之类的吗？

### ISSUE THREAD

**Issue by mjTree** [timxx/pywpsrpc#40]
Qt5 (C++ SDK依赖）,这个SDK可以到qt4上运行吗？还是需要必须在qt5才行

**Comment by timxx** [comment]
pywpsrpc绑定的是qt5的sdk，所以qt5是必须的。
官方貌似还有个qt4的sdk，感兴趣可以自己折腾一下
