### ISSUE TITLE
Call 'get_Documents()' failed with 0x80000008

### ISSUE THREAD

**Issue by zcgg2zhmm** [timxx/pywpsrpc#41]
**Describe the bug**
1. 我实在docker里面运行的，线上跑一段时间后，就会报错 Call 'get_Documents()' failed with 0x80000008，后来发现是因为wps进程不知道怎么关掉了，很神奇。
2. 上面的问题很好解决。后来又遇到wps进程没关掉，但是app变量又不是none，好像rpc失联了一样。
3. app变量没有quit，一直在内存里，为了节省启动wps的时间。
4. 感谢大佬，希望大佬帮忙中提供一些方案~~

**Comment by timxx** [comment]
得看是不是wos崩了，可以加点代码监听一下wps进程，rpc getProcessPid接口可以获取进程id

**Comment by zcgg2zhmm** [comment]
> 得看是不是wps崩了，可以加点代码监听一下wps进程，rpc getProcessPid接口可以获取进程id

好的，感谢，我来试试看

**Comment by zcgg2zhmm** [comment]
> 得看是不是wps崩了，可以加点代码监听一下wps进程，rpc getProcessPid接口可以获取进程id

@timxx 试了一下，rpc.getWpsApplication()调期wps以后，手动关掉wps，然后调用rpc.getProcessPid()，能得到以下tuple：
![image](https://user-images.githubusercontent.com/29967092/144217542-2643b6e8-0c3a-4bfa-8b91-0c2573b4f6a5.png)

但是后台确实是没有这个进程id了的，怎么确定wps是不是崩了呢？

**Comment by timxx** [comment]
这个方法只是告诉你wps的进程id，要自己用这个id去判断进程是不是挂了

**Comment by zcgg2zhmm** [comment]
> 这个方法只是告诉你wps的进程id，要自己用这个id去判断进程是不是挂了

@timxx ok~ 非常感谢！
