### ISSUE TITLE
arm64架构下安装失败

### ISSUE THREAD

**Issue by ColonelDarcy2018** [timxx/pywpsrpc#43]
**Describe the bug**
arm64架构下执行 pip install pywpsrpc 失败

**Screenshots**
![截图录屏_选择区域_20211228180159](https://user-images.githubusercontent.com/36758007/147556244-6134230f-6631-495e-8517-dd6da2b9a0d6.png)

**Environment**
 - Distribution: 统信uos
 - Versions: 20

**Comment by timxx** [comment]
目前只支持x64，我自己没有arm64的环境及SDK。。
