### ISSUE TITLE
发现只能在Ubuntu等具有sudo权限的用户下才能正确打开程序

### ISSUE THREAD

**Issue by vba34520** [timxx/pywpsrpc#44]
**Describe the bug**
发现只能在Ubuntu等具有sudo权限的用户下才能正确打开程序

报错
```
Convert failed:
Details: Can not get the application
ErrCode: 0x80000008
```

感谢您的工作！

**Comment by timxx** [comment]
> **Describe the bug**
> 发现只能在Ubuntu等具有sudo权限的用户下才能正确打开程序
> 
> 报错
> ```
> Convert failed:
> Details: Can not get the application
> ErrCode: 0x80000008
> ```
> 
> 感谢您的工作！

ubuntu多少？直接起wps可以么

**Comment by vba34520** [comment]
刚刚发现root用户也不能打开
感谢前辈，新年快乐~~

**Comment by timxx** [comment]
我试了下都没有问题，你看是不是没有把整合模式切换成多组件模式？这个readme有提到

**Comment by vba34520** [comment]
请问怎么切换？我找了很久都没找到

我的WPS为https://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/linux/10920/wps-office_11.1.0.10920.XA_amd64.deb

**Comment by vba34520** [comment]
设置多组件模式流程：`wps` → 右上角设置按钮 → Settings → Others → Change window manage mode...  → 选择【Multi-Module Mode】

![image](https://user-images.githubusercontent.com/40198281/152941092-bdb715b4-41ea-4c8b-8da8-7a6b328bd3b1.png)

![image](https://user-images.githubusercontent.com/40198281/152941106-cdb1ee62-8df3-414d-bf87-f8d7c10437de.png)

![image](https://user-images.githubusercontent.com/40198281/152941121-a5ab8859-68b6-4e44-be79-0f8049a249f2.png)

我这个版本默认模式为【Multi-Module Mode】

**Comment by vba34520** [comment]
参考Windows上的WPS长这样
![image](https://user-images.githubusercontent.com/40198281/152942834-8c41ff1a-4d43-4007-a826-1537bceb0c11.png)

**Comment by timxx** [comment]
> 设置多组件模式流程：`wps` → 右上角设置按钮 → Settings → Others → Change window manage mode... → 选择【Multi-Module Mode】
> 
> 我这个版本，wps-office_11.1.0.10920.XA_amd64.deb，默认模式为【Multi-Module Mode】
> 
> 可以分享一下您的测试版本下载链接吗？
> 
> ![image](https://user-images.githubusercontent.com/40198281/152941121-a5ab8859-68b6-4e44-be79-0f8049a249f2.png)





> 设置多组件模式流程：`wps` → 右上角设置按钮 → Settings → Others → Change window manage mode... → 选择【Multi-Module Mode】
> 
> 我这个版本，wps-office_11.1.0.10920.XA_amd64.deb，默认模式为【Multi-Module Mode】
> 
> 可以分享一下您的测试版本下载链接吗？
> 
> ![image](https://user-images.githubusercontent.com/40198281/152941121-a5ab8859-68b6-4e44-be79-0f8049a249f2.png)

同个版本的中文版，另外系统qt5也安装了吧？

**Comment by vba34520** [comment]
qt5也装了，谢谢提醒

我正在使用Flask开发一个Word转PDF的功能

均使用不同用户手动点击了用户说明那几步，接着用普通用户起了一个X11的进程，测试结果是：

成功：
- ubuntu用户+sudo

失败：
- ubuntu用户
- root用户
- root用户+sudo
- 其他用户

**Comment by timxx** [comment]
你这是server？

**Comment by vba34520** [comment]
是的

**Comment by timxx** [comment]
> 是的

server没有研究太多，毕竟wps本身就要求桌面。。

**Comment by vba34520** [comment]
谢谢前辈，Python调用C++的SDK，我想通过查阅文档看看有没有解决方案，现在有个问题是，貌似找不到官方文档了

**Comment by zcgg2zhmm** [comment]
> 谢谢前辈，Python调用C++的SDK，我想通过查阅文档看看有没有解决方案，现在有个问题是，貌似找不到官方文档了

https://open.wps.cn/docs/client/wpsLoad

**Comment by vba34520** [comment]
谢谢两位，祝好~

**Comment by w2918000** [comment]
我这边是在secureCRT的命令行模式下不行，用VNC连接桌面模式下，再打开个命令行调用就可以了 @timxx

**Comment by yibaiba** [comment]
要用root的话,要先用root用户在命令行里面输入 et,然后打开wps在改成组件模式, 普通用户 和 root用户的貌似是分开的,  然后在用
root权限起一个虚拟桌面 就可以转换了
