### ISSUE TITLE
{AttributeError}Call 'get_DistanceFrom()' failed with 0x80010105

### ISSUE THREAD

**Issue by mjTree** [timxx/pywpsrpc#46]
**Describe the bug**
在使用wps解析word文件时，通过Range类的Borders获取文本框与页面边缘距离时报错。
code:  document.Sections.Item(1)[1].Headers.Item(1)[1].Range.Borders.DistanceFrom
error: {AttributeError}Call 'get_DistanceFrom()' failed with 0x80010105

**Expected behavior**
应该通过设置wdBorderDistanceFromPageEdge获取文本框与页面距离。

**Screenshots**
![20220308195346](https://user-images.githubusercontent.com/30330903/157233389-7bf9c48f-175c-44e3-a7f1-2467c03a81fb.jpg)

**Environment**
ubuntu20
pywpsrpc: pip, 2.3.1
wps: 11.1.0.10920_amd64

**Comment by timxx** [comment]
可以提供个样张么。。怎么制作的。。。
（话说这个Item返回值有点蛋疼，搞的这么写 囧）

**Comment by timxx** [comment]
```python
doc.Sections[1].Borders[1].LineStyle = wpsapi.wdLineStyleSingle
#doc.Sections[1].Headers[1].Range.Borders.DistanceFrom = wpsapi.wdBorderDistanceFromPageEdge
doc.Sections[1].Borders.DistanceFrom = wpsapi.wdBorderDistanceFromPageEdge
```
上面这种写法是可以的，从[MSO官网](https://docs.microsoft.com/en-us/office/vba/api/word.borders.distancefrom)抄的例子
