### ISSUE TITLE
arm64系统上使用pip3 install pywpsrpc安装失败，有没有解决办法？

### ISSUE THREAD

**Issue by xupcc** [timxx/pywpsrpc#49]
**Describe the bug**
arm64系统上使用pip3 install pywpsrpc安装失败

usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 2.0.0kylin2 is an invalid version and will not be supported in a future release

  warnings.warn(

/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.23kylin1 is an invalid version and will not be supported in a future release

  warnings.warn(

Collecting pywpsrpc

  Using cached pywpsrpc-2.3.1.tar.gz (2.3 MB)

  Installing build dependencies ... done

  Getting requirements to build wheel ... done

    Preparing wheel metadata ... error

    ERROR: Command errored out with exit status 1:

     command: /usr/bin/python3 /tmp/tmpxjwi6tdv prepare_metadata_for_build_wheel /tmp/tmpep7_qjjq

         cwd: /tmp/pip-install-7tcy8lj3/pywpsrpc

    Complete output (3 lines):

    These bindings will be built: common, rpcwpsapi, rpcwppapi, rpcetapi.

    Generating the common bindings...

    tmpxjwi6tdv: /tmp/pip-install-7tcy8lj3/pywpsrpc/sip/common/common.sip: line 50 column 10: 'typedef' is unexpected

    ----------------------------------------

ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpxjwi6tdv prepare_metadata_for_build_wheel /tmp/tmpep7_qjjq Check the logs for full command output.

**Comment by timxx** [comment]
使用git取最新代码试试？

**Comment by timxx** [comment]
研究了下，发现是SIP >= 6.6版本的问题，暂时没有好的解决办法，你可以先将SIP降级到6.5的版本
`pip install sip==6.5.1`

**Comment by cole-dda** [comment]
<img width="426" alt="screenshot_5305" src="https://user-images.githubusercontent.com/1077830/173636474-af4477f0-0e6d-4c38-8d69-cf9721035716.png">

可以把这个修改为 sip==6.5.1 吗？因为自动安装总是使用最新的，需要手动下载，修改这个文件，或者先编译

**Comment by timxx** [comment]
> <img width="426" alt="screenshot_5305" src="https://user-images.githubusercontent.com/1077830/173636474-af4477f0-0e6d-4c38-8d69-cf9721035716.png">
> 
> 可以把这个修改为 sip==6.5.1 吗？因为自动安装总是使用最新的，需要手动下载，修改这个文件，或者先编译
> 
> 然后出现错误：
> AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
> 
> 而且，link的时候，需要rpcwpsapi_sysqt5.so  => wps的arm版本也没有这个库，ld总是失败
> 
> 是否可以提供一个arm64版本的wheel，可以直接通过pip安装即可？

sip已经推出了修复版本—6.6.2，现在用最新的应该也没问题了

**Comment by mjTree** [comment]
联系金山购买企业版即可
