### ISSUE TITLE
excel PageSetup设置属性无效果

### ISSUE THREAD

**Issue by mjTree** [timxx/pywpsrpc#52]
from pywpsrpc.rpcetapi import etapi

page_setup = etapi.PageSetup

excel列数较多时，通过ExportAsFixedFormat转换pdf文件会出现截取，对 page_setup的Zoom，FitToPagesWide等参数进行设置时，再转换也无法生效。

**Comment by timxx** [comment]
直接在软件上导出pdf是否有这个问题？
列数达到多少才会有问题呢。。

**Comment by mjTree** [comment]
> 直接在软件上导出pdf是否有这个问题？ 列数达到多少才会有问题呢。。

这边文件是10列，软件可以设置列数在一页，但是接口设置参数不生效。
![image](https://user-images.githubusercontent.com/30330903/174698884-e0f7bc26-d776-4395-8540-9dab06a46f24.png)

**Comment by timxx** [comment]
用Windows版本录制宏看了下，应该是设置下面这两个属性就可以了
``` python
ActiveSheet.PageSetup.FitToPagesWide = True
ActiveSheet.PageSetup.FitToPagesWall = True
```
但是现在的PageSetup确实是没有任何方法。。

**Comment by timxx** [comment]
@mjTree 你试试最新代码自己编译一个是不是正常了，我这边是可以了

**Comment by mjTree** [comment]
> 

好的，我这边先试一下，谢谢
