### ISSUE TITLE
关于获取excel文件的图表信息Charts

### ISSUE THREAD

**Issue by mjTree** [timxx/pywpsrpc#55]
[Charts.xlsx](https://github.com/timxx/pywpsrpc/files/9756408/Charts.xlsx)

这里有一个excel文件，但是打开Workbooks.Open('Charts.xlsx').Charts 为空。
![image](https://user-images.githubusercontent.com/30330903/195108557-99506114-4ef7-49b6-9604-bac997c8cb66.png)

不清楚是不是因为对应的sip文件没有定义，这边可以增加加吗？或者告知如何加我这边完成也可以。
https://github.com/timxx/pywpsrpc/blob/master/sip/rpcetapi/Charts.sip

**Comment by timxx** [comment]
抱歉我没有电脑暂时处理不了，你看下有没有对应ICharts或者带下划线的，有的话参考现有的做个映射（rpcetapi.sip里的），这个c++ sdk的接口比较坑。。文档也没有说那么细

**Comment by mjTree** [comment]
有ICharts.sip文件，但是不太清楚怎么映射

**Comment by timxx** [comment]
> 有ICharts.sip文件，但是不太清楚怎么映射

你看下我前面说的那个文件里面有那个啥convertto subclass之类的，抄一个应该就好了

**Comment by mjTree** [comment]
用了使用最新的v2.3.3版本，并没有解决这个问题，自己新建一个空白charts也无法打开或者操作那个chart对象。然后超时程序自动退出。

**Comment by timxx** [comment]
> 用了使用最新的v2.3.3版本，并没有解决这个问题，自己新建一个空白charts也无法打开或者操作那个chart对象。然后超时程序自动退出。

还没推新版本，还有一个问题还没时间分析
可以自己编译一个
