### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libQt5Network.so.5

### ISSUE THREAD

**Issue by caocb** [timxx/pywpsrpc#57]
报错位置：
from pywpsrpc.rpcwpsapi import (createWpsRpcInstance, wpsapi)
报错信息：
ImportError: /lib/x86_64-linux-gnu/libQt5Network.so.5: symbol _ZN15QIPAddressUtils8toStringER7QStringPh version Qt_5 not defined in file libQt5Core.so.5 with link time reference

比较奇怪的是，我只有在安装了pyqt5的环境中才会出现这个问题，其他环境使用正常。请问我该怎么解决？

**Comment by caocb** [comment]
经过测试，我发现是在安装了pyqt5的环境中，只要同时import了pyqt5和pywpsrpc.rpcwpsapi，就会报这个错；但是只import pywpsrpc.rpcwpsapi的话，程序一切正常。是pyqt5和pywpsrpc之间有什么关联吗？

**Comment by 12893822294** [comment]
我装了QT5，也是报这个错，那是不是我把QT卸载了或者把QT的环境变量删了就可以了

**Comment by timxx** [comment]
这是unix的通病吧，odr问题，不兼容的不同版本so不能加载到一起，因为wps提供的sdk本身依赖qt5，你可以自己编译一个pywpsrpc看看，用相同版本的qt
