### ISSUE TITLE
可以打包成.so文件吗

### ISSUE THREAD

**Issue by 12893822294** [timxx/pywpsrpc#60]
使用pywpsrpc开发的脚本 打包成.so文件运行，就会报错
NULL result without error in PyObject Call
有什么办法可以解决这个问题吗

**Comment by timxx** [comment]
> 使用pywpsrpc开发的脚本 打包成.so文件运行，就会报错
> NULL result without error in PyObject Call
> 有什么办法可以解决这个问题吗

具体出错截图跟示例有没有？

**Comment by 12893822294** [comment]
已经解决了，
Sheets[3] 当这里的3在excel中不存在时，即使加了try except Exception 也捕获不到异常
用.py就可以正常捕获异常
但是打包成so时，就捕获不到异常了
