### ISSUE TITLE
Range和IRange 两个有什么区别

### ISSUE THREAD

**Issue by 12893822294** [timxx/pywpsrpc#63]
我在使用AutoFill的时候，提示第一个参数要传etapi.Range
但我在使用Worksheet.Range()的时候，用type打印出来是IRange，
那我使用AutoFill的时候，不能传字符串的A1:A4，也不能传Range(A1:A4), 那应该传入什么

**Comment by timxx** [comment]
这是sdk的坑，暂时还没时间分析怎么处理
