### ISSUE TITLE
能否对统信UOS提供支持？统信无法使用pywpsrpc（已解决）

### ISSUE THREAD

**Issue by hyfdfajck** [timxx/pywpsrpc#66]
统信UOS直接使用pip安装pywpsrpc时，它提示找不到“librpcwpsapi_sysqt5”，我认为原因是统信中wps安装在/opt/apps/cn.wps.wps-office-pro/files/kingsoft/wps-office/office6，pywpsrpc在默认的位置找不到wps。这两天尝试在电脑重新编译pywpsrpc，把project.py文件中第39行中的dir那里进行修改，但统信系统跟其他系统可能不一样，sip-build到最后就提示出错，我看到build文件夹里有makefile，试着直接make，提示找不到qcoreapplication，勉强解决了又提示找不到python.h，这个问题半天搜不到解决方案。
请求作者对统信提供支持。（hyfdajck@163.com）

**Comment by timxx** [comment]
你要先安装qt5跟python的开发包，我这边没有统信的环境，按理都是一样的

**Comment by hyfdfajck** [comment]
装完QT5和python-dev，编译完成了，生成了whl文件，安装完了，但我的代码一运行还是提示：

**Comment by hyfdfajck** [comment]
raceback (most recent call last):
  File "work.py", line 5, in <module>
    from pywpsrpc import rpcwpsapi
ImportError: librpcwpsapi_sysqt5.so: cannot open shared object file: No such file or directory

**Comment by hyfdfajck** [comment]
把/opt/apps/cn.wps.wps-office-pro/files/kingsoft/wps-office/office6目录下的librpcwpsapi_sysqt5拷到site-package/pywpsrpc目录里，然后因为系统使用的qt5版本是5.11.3，所以重新pip install pyqt5==5.11.3。至少目前运行起来正常了。不过5.11.3有点旧，pyqt5-tools这个版本没有linux的，只有win的。。。。。

**Comment by timxx** [comment]
> 把/opt/apps/cn.wps.wps-office-pro/files/kingsoft/wps-office/office6目录下的librpcwpsapi_sysqt5拷到site-package/pywpsrpc目录里，然后因为系统使用的qt5版本是5.11.3，所以重新pip install pyqt5==5.11.3。至少目前运行起来正常了。不过5.11.3有点旧，pyqt5-tools这个版本没有linux的，只有win的。。。。。

可以设置rpath，现在只加了常规安装目录的
