### ISSUE TITLE
在worksheet调用get_Range，希望获取某一行单元格的所有值时出现问题

### ISSUE THREAD

**Issue by suqi95716aa** [timxx/pywpsrpc#69]
**Describe the bug**
在worksheet调用get_Range，希望获取某一行单元格的所有值时出现问题
比如
hr, cells = ws.get_Range("A1:A7")
cells.Value
会得到错误
AttributeError: Call 'get_Value()' failed with 0x80000003,
但是只获取一个单元格没有问题
hr, cells = ws.get_Range("A1")
cells.Value
可以正确获得值

**Environment**
 - Distribution: UOS系统 18.04
 - Versions: [e.g. pywpsrpc 3.2.3, WPS表格 11.1.0.11691]
 - Installed from pip: [yes/build from source]

**Comment by timxx** [comment]
请更新到最新版本，问题已经处理过了。
#62 写二维数组目前Linux版本WPS还有BUG（确认是客户端的问题）

**Comment by suqi95716aa** [comment]
> 请更新到最新版本，问题已经处理过了。 #62 写二维数组目前Linux版本WPS还有BUG（确认是客户端的问题）

在更新到最新版本的pywpsrpc==2.3.5后，报出错误`ImportError: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not fo`，之后把PyQT5替换到5.12版本之后这个问题仍未解决

**Comment by timxx** [comment]
现在是因为github不支持ubuntu 18.04了，依赖的qt5版本变高， 你要升级的是系统的qt5，不是pyqt5（pywpsrpc没有依赖它），或者用自己的环境编译一个pywpsrpc

**Comment by suqi95716aa** [comment]
> 

感谢

**Comment by guohailin0323** [comment]
> 请更新到最新版本，问题已经处理过了。 #62 写二维数组目前Linux版本WPS还有BUG（确认是客户端的问题）

获取一列单元格的所有值还有这个问题，获取一个单元格的值是没问题的。
ws.Range("B1:B7").Value
报错:"AttributeError: Call 'get_Value()' failed with 0x80000003,"

备注:
获取一行单元格的所有值是正常的，例: ws.Range("A1:E1").Value
pywpsrpc版本：2.3.6
UOS系统
WPS:11.1.0.11698

**Comment by timxx** [comment]
> > 请更新到最新版本，问题已经处理过了。 #62 写二维数组目前Linux版本WPS还有BUG（确认是客户端的问题）
> 
> 获取一列单元格的所有值还有这个问题，获取一个单元格的值是没问题的。 ws.Range("B1:B7").Value 报错:"AttributeError: Call 'get_Value()' failed with 0x80000003,"
> 
> 备注: 获取一行单元格的所有值是正常的，例: ws.Range("A1:E1").Value pywpsrpc版本：2.3.6 UOS系统 WPS:11.1.0.11698

新问题应该新报一个issue..
