### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'Documents'

### ISSUE THREAD

**Issue by ruizgo** [timxx/pywpsrpc#7]
运行demo在Debian\Centos\Ubuntu出现如下报错：
```
Traceback (most recent call last):
  File "2.py", line 25, in <module>
    hr, doc = app.Documents.Add()
AttributeError: 'NoneType' object has no attribute 'Documents'
```
是什么原因造成的呢？

**Comment by ruizgo** [comment]
运行python3 convertto.py --format "pdf" README.md
`Convert failed:
Details: Can't get the application
ErrCode: 0x80000008`

**Comment by timxx** [comment]
请确保安装有桌面环境，WPS能够正常运行；另外需要多组件模式。README都有写

**Comment by ruizgo** [comment]
> 
> 
> 请确保安装有桌面环境，WPS能够正常运行；另外需要多组件模式。README都有写

谢谢，已经可以正常生成。

**Comment by xiaobing395845388** [comment]
你好，遇到了同样的问题，请教下怎么解决的？

**Comment by xiaobing395845388** [comment]
@ruizgo
