### ISSUE TITLE
支持ARM架构吗，我在执行sip-build的时候一直报错

### ISSUE THREAD

**Issue by 12893822294** [timxx/pywpsrpc#70]
![image](https://github.com/timxx/pywpsrpc/assets/38283048/ac6beb79-070c-4146-bcdd-06ba1b84cfe2)

sip-6.7.4
qt-5.11
qmake-3.1
g++-8.3
有谁知道这个是什么问题吗

**Comment by 12893822294** [comment]
解决了，是因为wps的路径问题 `project.py`的 /opt/apps/cn.wps.wps-office 改成/opt/apps/cn.wps.wps-office-pro就可以了

**Comment by 12893822294** [comment]
还有一个其他问题，wpsrpc-sdk/lib/x86_64/ 里面的文件是不是只有在X86的下面才用到，在ARM架构上是不是用不到
我运行的时候报错：ImportError: librpcetapi_sysqt5.so: cannot open shared object file: No such file or directory

**Comment by 12893822294** [comment]
解决了，手动把wps-office6下面的依赖的动态库拷过来就行了

**Comment by guohailin0323** [comment]
> 解决了，手动把wps-office6下面的依赖的动态库拷过来就行了

你好，
   你用的wps企业版么?wps企业版支持arm架构?

**Comment by 12893822294** [comment]
不是，是专业版

**Comment by guohailin0323** [comment]
> 不是，是专业版
也就说用arm wps专业版， 就能编译pywpsrpc，可以正常的调用pywpsrpc的接口了，对吧

**Comment by 12893822294** [comment]
嗯   跑通了  一直在用

**Comment by guohailin0323** [comment]
> 嗯 跑通了 一直在用

厉害，我准备也这样搞 试试。

**Comment by guohailin0323** [comment]
> 嗯 跑通了 一直在用

请问arm平台编译，project.py还有其他要修改的么。

在arm平台编译生成了pywpsrpc-2.3.9-cp38-cp38-manylinux_2_5_aarch64.whl，
pip3 install pywpsrpc-*.whl报错了，"pywpsrpc-2.3.9-cp38-cp38-manylinux_2_5_aarch64.whl is not a supported wheel on this platform"

**Comment by guohailin0323** [comment]
解决了，要修改下文件名为pywpsrpc-2.3.9-cp38-cp38-linux_aarch64.whl

**Comment by fahaihappy** [comment]
@12893822294 你是在wps买的专业版吗

**Comment by guohailin0323** [comment]
> @12893822294 你是在wps买的专业版吗

应用市场可以安装专业版

**Comment by fahaihappy** [comment]
您好  您的邮件我已收到   谢谢！！！
