### ISSUE TITLE
设置excel行列隐藏报错，Shape对象获取错误

### ISSUE THREAD

**Issue by Smilerare** [timxx/pywpsrpc#73]
1.设置excel行列隐藏报错Call'put_Hidden()'failed with 0x80010105
Worksheets.Range("C").Hidden = True
2.Worksheets.Shapes获取excel中Shape对象会有一个None对象，导致少了一个对象
比如excel中只有一张图片，Worksheets.Shapes.Item(0)返回None

**Comment by timxx** [comment]
第二点，索引本来就是从1开始的，readme有说，这个跟C++的一致（vb遗传的产物），没有特意处理

**Comment by timxx** [comment]
第一点，应该是你写的代码有问题？我这里用最新版本测试是没有问题的
![image](https://github.com/timxx/pywpsrpc/assets/1598262/4c059486-19e6-4916-acdb-cb763f452e00)

**Comment by Smilerare** [comment]
> 第一点，应该是你写的代码有问题？我这里用最新版本测试是没有问题的 ![image](https://user-images.githubusercontent.com/1598262/245364804-4c059486-19e6-4916-acdb-cb763f452e00.png)

> 刚刚编译的最新代码，能帮我看看哪里的问题吗

![1](https://github.com/timxx/pywpsrpc/assets/47654501/bea6199e-23e7-43ab-b2f7-ae2c7112bc60)
