### ISSUE TITLE
透视表：PivotFields返回值有问题

### ISSUE THREAD

**Issue by guohailin0323** [timxx/pywpsrpc#77]
ptFlds = pt.PivotFields()
count = ptFlds[1].Count

报错:"IDispatch object has no attribute Count"
ptFlds为(0, pywpsrpc.common.IDispatch object at 0x7f5b90c31dc8)
ptFlds 是 有问题的

UOS系统
pywpsrpc 2.3.7
WPS 11.1.0.11698

**Comment by timxx** [comment]
这个是因为坑爹的SDK提供的接口返回的是IDispatch类型参数，目前python里还不支持QueryInterface（即使支持了使用也不方便）
所以目前暂时只能一个个处理（针对有需求的）。。
如果你使用遇到新的，也可以参考这改动记录处理下，并不复杂，欢迎PR

**Comment by guohailin0323** [comment]
这个修复大约什么时候发版呢，可以尽快发一个版本么，我的需求功能 就缺这个了
