### ISSUE TITLE
【编译】运行时依赖的Qt版本只能Qt5.12, 是哪里有限制么? 可以手动依赖Qt5.11编译么

### ISSUE THREAD

**Issue by guohailin0323** [timxx/pywpsrpc#79]
系统带的Qt版本是Qt5.11，运行时报错找不到Qt5.12

UOS系统
pywpsrpc 2.3.8
WPS 11.1.0.11698

**Comment by guohailin0323** [comment]
有手动安装Qt5.12，并且设置rpath，仍然报错找不到qt5.12，感觉还是去系统目录下搜索了

**Comment by timxx** [comment]
请自行在所需环境编译
