### ISSUE TITLE
word中公式对象OMath的方法异常

### ISSUE THREAD

**Issue by mjTree** [timxx/pywpsrpc#82]
**Describe the bug**
word文档中，随便插入一个公式，通过range对象的OMaths[1]获取公式对象，对象的ConvertToMathText等方法返回值不是字符串而是数字0。
[https://learn.microsoft.com/zh-cn/office/vba/api/word.omath.converttomathtext](url)

**Screenshots**
![image](https://github.com/timxx/pywpsrpc/assets/30330903/92f90c9e-574a-425c-991f-4d0e2d55cb0f)

**Environment**
 - Ubuntu 20
 - Versions: [pywpsrpc 2.3.3和2.3.9，WPS Office 11.1.0.10920]
 - Installed from pip: [2.3.3来自源码编译，2.3.9来自pip安装]

**Comment by akkuman** [comment]
wps方法有点不同，你可以查看https://open.wps.cn/docs/client/wpsLoad 看看接口文档，一般获取 Document 中某个属性后，不能直接像com+msoffice那样直接 `[1]`，大多数情况都是 `ret, x = doc.xxx; x.Item(1)`

**Comment by mjTree** [comment]
> wps方法有点不同，你可以查看https://open.wps.cn/docs/client/wpsLoad 看看接口文档，一般获取 Document 中某个属性后，不能直接像com+msoffice那样直接 `[1]`，大多数情况都是 `ret, x = doc.xxx; x.Item(1)`

谢谢回答，但是itme是js的写法，py的可以需要。作者以前也是说过，接口文档优先微软更齐全。

**Comment by akkuman** [comment]
因为这个库是直接用wps的c++接口生成的，所以是需要看c++的那份接口文档

**Comment by timxx** [comment]
公式相关的接口，Windows版本WPS都还没实现~
另外，如果你想跟VB接口一样调用，可以用[RpcProxy](https://github.com/timxx/pywpsrpc/wiki/RpcProxy)包装一下
