### ISSUE TITLE
xls,xlsx 转pdf问题 

### ISSUE THREAD

**Issue by CYCAC** [timxx/pywpsrpc#88]
请问当表格类型的文件转PDF 能有参数可以选择横向或者将所有行都放在一列 的选项吗

**Comment by mjTree** [comment]
> 请问当表格类型的文件转PDF 能有参数可以选择横向或者将所有行都放在一列 的选项吗

https://learn.microsoft.com/zh-cn/office/vba/api/excel.pagesetup.orientation

**Comment by CYCAC** [comment]
> > 请问当表格类型的文件转PDF 能有参数可以选择横向或者将所有行都放在一列 的选项吗
> 
> https://learn.microsoft.com/zh-cn/office/vba/api/excel.pagesetup.orientation

大佬 请问 这个里面的接口我应该怎么用pywpsrpc 这个包去调用 非常期望得到您的解答

**Comment by mjTree** [comment]
> > > 请问当表格类型的文件转PDF 能有参数可以选择横向或者将所有行都放在一列 的选项吗
> > 
> > 
> > https://learn.microsoft.com/zh-cn/office/vba/api/excel.pagesetup.orientation
> 
> 大佬 请问 这个里面的接口我应该怎么用pywpsrpc 这个包去调用 非常期望得到您的解答

```python
from pywpsrpc.rpcetapi import createEtRpcInstance
from pywpsrpc.rpcetapi import etapi

result, et_rpc = createEtRpcInstance()
result, app_excel = et_rpc.getEtApplication()
result, workbook = app_excel.Workbooks.Open(excel_path)
app_excel.Worksheets[0].PageSetup.Orientation = etapi. xlLandscape    # 设置横向
```
