### ISSUE TITLE
centos8下 word转PDF的会有一部分超出变成第二页

### ISSUE THREAD

**Issue by EthanTong1** [timxx/pywpsrpc#95]
win下用wps软件手动把word转成PDF是正常的, 通过linux下代码转出来会有部分页面超出变成两页

请问有什么好的方法可以解决一下吗

**Comment by kevinhonor** [comment]
> win下用wps软件手动把word转成PDF是正常的, 通过linux下代码转出来会有部分页面超出变成两页
> 
> 请问有什么好的方法可以解决一下吗

需要把win下的字体拷贝一份给wps

**Comment by timxx** [comment]
确保文档用到的字体都有安装，如果页数还是不一致，可以给wps官方反馈
